[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "tslgen"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
	"cyclopts",
	"lark>=1.3",
	"PyYAML>=6",
]

[project.scripts]
tslgen = "tslgen.cli:run"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
tslgen = ["syntax/grammar/*.lark"]
