"""Backend emitters and translation helpers for the clean restart generator."""

from tslgen.backends.type_spelling import (
    BackendTranslatedTypeSpelling,
    BackendTypeSpellingMetadataKind,
    BackendTypeSpellingTranslationBatchResult,
    BackendTypeSpellingTranslationResult,
    translate_backend_type_spelling_request,
    translate_backend_type_spelling_requests,
)
from tslgen.backends.value_translation import (
    BackendTranslatedValue,
    BackendValueText,
    BackendValueTranslationBatchResult,
    BackendValueTranslationResult,
    translate_backend_value_request,
    translate_backend_value_requests,
)
from tslgen.backends.intrinsic_modifiers import (
    BackendIntrinsicImmediateLiteral,
    BackendIntrinsicInfixSeparator,
    BackendIntrinsicInfixSeparatorText,
    BackendIntrinsicLiteralFragment,
    BackendIntrinsicModifierFragmentText,
    BackendIntrinsicModifierTranslationBatchResult,
    BackendIntrinsicModifierTranslationResult,
    BackendTranslatedIntrinsicModifier,
    BackendTranslatedIntrinsicModifierValue,
    translate_backend_intrinsic_compose_modifiers,
    translate_backend_intrinsic_handoff_request_modifiers,
    translate_backend_intrinsic_modifier_field,
    translate_backend_intrinsic_modifier_fields,
)

__all__ = [
    "BackendIntrinsicImmediateLiteral",
    "BackendIntrinsicInfixSeparator",
    "BackendIntrinsicInfixSeparatorText",
    "BackendIntrinsicLiteralFragment",
    "BackendIntrinsicModifierFragmentText",
    "BackendIntrinsicModifierTranslationBatchResult",
    "BackendIntrinsicModifierTranslationResult",
    "BackendTranslatedTypeSpelling",
    "BackendTranslatedIntrinsicModifier",
    "BackendTranslatedIntrinsicModifierValue",
    "BackendTranslatedValue",
    "BackendTypeSpellingMetadataKind",
    "BackendTypeSpellingTranslationBatchResult",
    "BackendTypeSpellingTranslationResult",
    "BackendValueText",
    "BackendValueTranslationBatchResult",
    "BackendValueTranslationResult",
    "translate_backend_intrinsic_compose_modifiers",
    "translate_backend_intrinsic_handoff_request_modifiers",
    "translate_backend_intrinsic_modifier_field",
    "translate_backend_intrinsic_modifier_fields",
    "translate_backend_type_spelling_request",
    "translate_backend_type_spelling_requests",
    "translate_backend_value_request",
    "translate_backend_value_requests",
]
