// Generated by tslgen clean-room production-test slice.
// Backend: cpp
// Artifact: tests/production_tests.cpp
// Artifact kind: production_tests
// Planned tests: 2
// Supported slice: scalar binary si32/ui32 metadata tests

#include <cstddef>

namespace tsl {
namespace generated_tests {

struct scalar_binary_case {
  const char* test_name;
  const char* primitive;
  const char* function_name;
  const char* candidate_id;
  const char* target_extension;
  const char* source_extension;
  const char* type_tag;
  const char* lane_set;
  unsigned int lanes;
  const char* left_values;
  const char* right_values;
  const char* expected_values;
};

inline constexpr scalar_binary_case scalar_binary_cases[] = {
  {
    "planned_add_i32_basic",
    "planned_add",
    "planned_add_si32",
    "planned_add<v:=(v,v)>[](left,right)|backend=cpp|target=scalar|source=scalar|type=si32|flags=none|impl=scalar/si32/tsil",
    "scalar",
    "scalar",
    "si32",
    "lanes_i32",
    8,
    "[1, 2]",
    "[3, 4]",
    "[4, 6]",
  },
  {
    "planned_add_ui32_basic",
    "planned_add",
    "planned_add_ui32",
    "planned_add<v:=(v,v)>[](left,right)|backend=cpp|target=scalar|source=scalar|type=ui32|flags=none|impl=scalar/ui32/tsil",
    "scalar",
    "scalar",
    "ui32",
    "lanes_i32",
    8,
    "[5, 6]",
    "[7, 8]",
    "[12, 14]",
  },
};

}  // namespace generated_tests
}  // namespace tsl
