from __future__ import annotations

from tslgen.analysis.candidates import ImplementationCandidate
from tslgen.core.frozen_map import FrozenMap
from tslgen.core.result import Result
from tslgen.io.artifacts import Artifact, ArtifactSet, artifact_set_from_artifacts

from .bodies import render_cpp_production_definitions
from .declarations import render_cpp_production_declarations
from .planner import CppRenderJob, CppRenderPlan


def render_cpp_plan(plan: CppRenderPlan) -> Result[ArtifactSet]:
    artifacts = tuple(_render_job(job) for job in plan.jobs)
    return artifact_set_from_artifacts(artifacts, metadata=plan.metadata)


def _render_job(job: CppRenderJob) -> Artifact:
    content = _render_generated_header(job)
    return Artifact(
        logical_path=job.descriptor.logical_path,
        content=content,
        metadata=FrozenMap(
            {
                "artifact_kind": job.descriptor.kind,
                "backend_id": "cpp",
                "candidate_count": len(job.candidates),
                "definition_count": len(job.definitions),
                "required_flags": _required_flag_names(job.candidates),
                "target_extensions": _target_extension_names(job.candidates),
            }
        ),
    )


def _render_generated_header(job: CppRenderJob) -> str:
    required_flags = _csv(_required_flag_names(job.candidates))
    target_extensions = _csv(_target_extension_names(job.candidates))
    lines = [
        "// Generated by tslgen clean-room backend slice.",
        "// Backend: cpp",
        f"// Artifact: {job.descriptor.logical_path.as_posix()}",
        f"// Artifact kind: {job.descriptor.kind}",
        f"// Candidates: {len(job.candidates)}",
        f"// Definitions: {len(job.definitions)}",
        f"// Required flags: {required_flags}",
        f"// Target extensions: {target_extensions}",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace tsl {",
        "namespace generated {",
        "",
        "struct primitive_candidate {",
        "  const char* primitive;",
        "  const char* template_name;",
        "  const char* target_extension;",
        "  const char* source_extension;",
        "  const char* type_tag;",
        "  const char* required_flags;",
        "  const char* body_kind;",
        "  const char* opaque_tsil_payload;",
        "};",
        "",
        "inline constexpr primitive_candidate primitive_candidates[] = {",
    ]
    for candidate in job.candidates:
        lines.extend(_candidate_lines(candidate))
    lines.extend(
        [
            "};",
            "",
        ]
    )
    production_lines = render_cpp_production_definitions(job.definitions)
    if not production_lines:
        production_lines = render_cpp_production_declarations(job.declarations)
    if production_lines:
        lines.extend((*production_lines, ""))
    lines.extend(
        [
            "}  // namespace generated",
            "}  // namespace tsl",
            "",
        ]
    )
    return "\n".join(lines)


def _candidate_lines(candidate: ImplementationCandidate) -> tuple[str, ...]:
    body = candidate.implementation.body
    payload = body.text or ""
    required_flags = _csv(tuple(flag.name for flag in candidate.required_flags))
    return (
        "  {",
        f"    {_cpp_string(candidate.emitted_primitive_name)},",
        f"    {_cpp_string(candidate.template_name)},",
        f"    {_cpp_string(candidate.target_extension)},",
        f"    {_cpp_string(candidate.source_extension)},",
        f"    {_cpp_string(candidate.type_tag)},",
        f"    {_cpp_string(required_flags)},",
        f"    {_cpp_string(body.kind)},",
        f"    {_cpp_string(payload)},",
        "  },",
    )


def _required_flag_names(
    candidates: tuple[ImplementationCandidate, ...],
) -> tuple[str, ...]:
    return tuple(
        sorted(
            {
                flag.name
                for candidate in candidates
                for flag in candidate.required_flags
            }
        )
    )


def _target_extension_names(
    candidates: tuple[ImplementationCandidate, ...],
) -> tuple[str, ...]:
    return tuple(sorted({candidate.target_extension for candidate in candidates}))


def _csv(values: tuple[str, ...]) -> str:
    return ", ".join(values) if values else "none"


def _cpp_string(value: str) -> str:
    replacements: dict[str, str] = {
        "\\": "\\\\",
        '"': '\\"',
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
    }
    escaped = "".join(replacements.get(character, character) for character in value)
    return f'"{escaped}"'
