// Generated by tslgen clean-room C++ test-source parity slice.
// Backend: cpp
// Artifact: tests/add_i32_basic_test.cpp
// Artifact kind: production_tests
// Parity baseline: CPP-ADD-I32-TEST

#include <cstddef>
#include <cstdint>
#include <gtest/gtest.h>

static bool test_add_i32_basic() {
  using Vec = tsl::simd<int32_t, scalar>;
  constexpr std::size_t kCount = Vec::vector_element_count();
  const int32_t in_a[kCount] = {1, 2, 3, 4, 5, 6, 7, 8};
  const int32_t in_b[kCount] = {8, 7, 6, 5, 4, 3, 2, 1};
  const int32_t expected_values[kCount] = {9, 9, 9, 9, 9, 9, 9, 9};

  auto a = tsl::load_aligned_false<Vec>(in_a);
  auto b = tsl::load_aligned_false<Vec>(in_b);
  auto c = tsl::add<Vec>(a, b);
  int32_t out[kCount] = {};
  tsl::store_aligned_false<Vec>(out, c);

  for (std::size_t i = 0; i < kCount; ++i) {
    if (out[i] != expected_values[i]) {
      return false;
    }
  }
  return true;
}

TEST(TslGeneratedTests, add_i32_basic) {
  ASSERT_TRUE(test_add_i32_basic());
}
