//! Fail-closed build-time consumption of precomputed Rust variant policies.

use std::collections::HashSet;
use std::ffi::OsString;
use std::fs::{File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use crate::tsl_rust_policy_json::MAX_JSON_INPUT_BYTES;
use crate::tsl_rust_variant_policy_protocol::{parse_descriptor, parse_policy};
use crate::tsl_rust_variant_policy_validation::{
    validate_descriptor, validate_native_context, validate_policy,
};

// These declarations are the generated build-script interface. An empty policy
// inventory intentionally leaves the mapping-specific declarations unused.
#[allow(unused_imports)]
pub use crate::tsl_rust_variant_policy_protocol::{
    BuildContext, GeneratedMapping, GeneratedProfile, GeneratedTargetRequirement,
};

pub fn consume_policy(
    policy_input: OsString,
    manifest_dir: &Path,
    out_dir: &Path,
    context: &BuildContext,
    profiles: &'static [GeneratedProfile],
) -> Result<PathBuf, String> {
    let active = active_profile(profiles)?;
    validate_native_context(context)?;

    let input = policy_input
        .into_string()
        .map_err(|_| "TSL_RUST_VARIANT_POLICY_FILE must be valid UTF-8".to_string())?;
    if input.is_empty() {
        return Err("TSL_RUST_VARIANT_POLICY_FILE is present but empty".to_string());
    }
    let policy_path = resolve_input_path(manifest_dir, &input);
    emit_rerun_if_changed(&policy_path, "Rust variant policy")?;
    let policy_bytes = read_regular_snapshot(&policy_path, "Rust variant policy")?;
    let policy_text = std::str::from_utf8(&policy_bytes)
        .map_err(|_| "Rust variant policy must be UTF-8 JSON".to_string())?;
    let policy = parse_policy(policy_text)?;

    // `include_str!` embeds the compiler-produced descriptor in the build-script
    // binary.  Policy input can select only mapping source that was present when
    // this build script was compiled; it cannot replace mapping source by racing
    // or editing a runtime sidecar after compilation.
    emit_rerun_if_changed(
        &manifest_dir.join(active.descriptor_relative_path),
        "generated Rust policy-consumption descriptor",
    )?;
    let descriptor = parse_descriptor(active.descriptor)?;

    validate_descriptor(&descriptor, active, context)?;
    let mapping = validate_policy(&policy, &descriptor, active, context)?;

    if read_regular_snapshot(&policy_path, "Rust variant policy")? != policy_bytes {
        return Err("Rust variant policy changed while it was being validated".to_string());
    }
    materialize_mapping(out_dir, active, &mapping)
}

pub fn materialize_default_mapping(
    out_dir: &Path,
    profiles: &'static [GeneratedProfile],
) -> Result<Option<PathBuf>, String> {
    let Some(active) = active_profile_or_none(profiles)? else {
        return Ok(None);
    };
    let mut stable_ids = HashSet::new();
    let mut default_ids = HashSet::new();
    let mut mapping =
        String::from("// Generated by tslc build-time Rust authored-default selection.\n");
    for candidate in active.mappings {
        if candidate.stable_id.is_empty()
            || candidate.candidate.is_empty()
            || candidate.source.trim().is_empty()
        {
            return Err("generated Rust default mapping inventory has an empty entry".to_string());
        }
        stable_ids.insert(candidate.stable_id);
        if candidate.candidate == "default" {
            if !default_ids.insert(candidate.stable_id) {
                return Err(
                    "generated Rust default mapping inventory has duplicate defaults".to_string(),
                );
            }
            mapping.push_str(candidate.source);
            mapping.push_str("\n\n");
        }
    }
    if stable_ids.is_empty() || stable_ids != default_ids {
        return Err("generated Rust default mapping inventory is stale or incomplete".to_string());
    }
    materialize_mapping(out_dir, active, &mapping).map(Some)
}

fn active_profile(
    profiles: &'static [GeneratedProfile],
) -> Result<&'static GeneratedProfile, String> {
    active_profile_or_none(profiles)?.ok_or_else(|| {
        "Rust policy consumption requires one generated compile-target profile; found 0"
            .to_string()
    })
}

fn active_profile_or_none(
    profiles: &'static [GeneratedProfile],
) -> Result<Option<&'static GeneratedProfile>, String> {
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH")
        .map_err(|_| "Cargo did not provide CARGO_CFG_TARGET_ARCH".to_string())?;
    let target_features = std::env::var("CARGO_CFG_TARGET_FEATURE")
        .unwrap_or_default()
        .split(',')
        .filter(|feature| !feature.is_empty())
        .map(str::to_string)
        .collect::<HashSet<_>>();
    let active = profiles
        .iter()
        .filter(|profile| {
            target_matches(
                profile.target_arch,
                profile.target_features,
                &target_arch,
                &target_features,
            ) && !profile.stronger_requirements.iter().any(|requirement| {
                target_matches(
                    requirement.target_arch,
                    requirement.target_features,
                    &target_arch,
                    &target_features,
                )
            })
        })
        .collect::<Vec<_>>();
    if active.len() > 1 {
        return Err(format!(
            "Rust policy consumption requires exactly one compile-target profile; found {}",
            active.len()
        ));
    }
    Ok(active.into_iter().next())
}

fn target_matches(
    required_arch: &str,
    required_features: &[&str],
    target_arch: &str,
    target_features: &HashSet<String>,
) -> bool {
    required_arch == target_arch
        && required_features
            .iter()
            .all(|feature| target_features.contains(*feature))
}

fn resolve_input_path(manifest_dir: &Path, input: &str) -> PathBuf {
    let path = Path::new(input);
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        manifest_dir.join(path)
    }
}

fn emit_rerun_if_changed(path: &Path, label: &str) -> Result<(), String> {
    let value = path
        .to_str()
        .ok_or_else(|| format!("{label} path must be valid UTF-8"))?;
    if value.contains('\n') || value.contains('\r') {
        return Err(format!(
            "{label} path cannot contain line breaks in a Cargo directive"
        ));
    }
    println!("cargo:rerun-if-changed={}", value);
    Ok(())
}

fn read_regular_snapshot(path: &Path, label: &str) -> Result<Vec<u8>, String> {
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| format!("cannot inspect {label} {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() || !metadata.file_type().is_file() {
        return Err(format!(
            "{label} {} must be a non-symlink regular file",
            path.display()
        ));
    }
    if metadata.len() > MAX_JSON_INPUT_BYTES as u64 {
        return Err(format!(
            "{label} {} exceeds the {}-byte policy limit",
            path.display(),
            MAX_JSON_INPUT_BYTES
        ));
    }
    let input = File::open(path)
        .map_err(|error| format!("cannot open {label} {}: {error}", path.display()))?;
    let mut bytes = Vec::with_capacity(metadata.len() as usize);
    input
        .take(MAX_JSON_INPUT_BYTES as u64 + 1)
        .read_to_end(&mut bytes)
        .map_err(|error| format!("cannot read {label} {}: {error}", path.display()))?;
    if bytes.len() > MAX_JSON_INPUT_BYTES {
        return Err(format!(
            "{label} {} exceeds the {}-byte policy limit",
            path.display(),
            MAX_JSON_INPUT_BYTES
        ));
    }
    Ok(bytes)
}

fn materialize_mapping(
    out_dir: &Path,
    profile: &GeneratedProfile,
    mapping: &str,
) -> Result<PathBuf, String> {
    let path = out_dir.join(profile.materialized_mapping_file);
    match std::fs::symlink_metadata(&path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.file_type().is_file() {
                return Err(format!(
                    "Rust policy mapping {} must be a non-symlink regular file",
                    path.display()
                ));
            }
            let existing = std::fs::read(&path).map_err(|error| {
                format!(
                    "cannot verify existing Rust policy mapping {}: {error}",
                    path.display()
                )
            })?;
            if existing == mapping.as_bytes() {
                return Ok(path);
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(format!(
                "cannot inspect Rust policy mapping {}: {error}",
                path.display()
            ));
        }
    }
    let mut output = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(&path)
        .map_err(|error| {
            format!(
                "cannot create Rust policy mapping {}: {error}",
                path.display()
            )
        })?;
    output.write_all(mapping.as_bytes()).map_err(|error| {
        format!(
            "cannot write Rust policy mapping {}: {error}",
            path.display()
        )
    })?;
    output.sync_all().map_err(|error| {
        format!(
            "cannot sync Rust policy mapping {}: {error}",
            path.display()
        )
    })?;
    Ok(path)
}
