// Generated by tslgen clean-room backend slice.
// Backend: rust
// Artifact: generated.rs
// Artifact kind: generated
// Candidates: 1
// Declarations: 1
// Required flags: sse
// Target extensions: scalar

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PrimitiveCandidate {
    pub primitive: &'static str,
    pub template_name: &'static str,
    pub target_extension: &'static str,
    pub source_extension: &'static str,
    pub type_tag: &'static str,
    pub required_flags: &'static str,
    pub body_kind: &'static str,
    pub opaque_tsil_payload: &'static str,
}

pub const PRIMITIVE_CANDIDATES: &[PrimitiveCandidate] = &[
    PrimitiveCandidate {
        primitive: "slice_add",
        template_name: "binary",
        target_extension: "scalar",
        source_extension: "scalar",
        type_tag: "si32",
        required_flags: "sse",
        body_kind: "tsil",
        opaque_tsil_payload: "emit_return(left + right);",
    },
];

pub mod production {
    pub trait ScalarBinaryDeclarations {
        fn slice_add_si32(left: i32, right: i32) -> i32;
    }
}
