"""Typed specialization inventory calculation and command behavior."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tslc.catalog.model import Catalog, Implementation, Primitive
from tslc.maintenance import coverage_inventory
from tslc.maintenance.coverage_inventory_report import (
    CoverageInventory,
    build_coverage_inventory,
)
from tslc.maintenance.coverage_inventory_render import (
    render_json,
    render_markdown,
    render_text,
)
from tslc.output.artifacts import ArtifactSet
from tslc.pipeline import CoverageEntry, GenerationResult, SkippedEntry


def _primitive(name: str) -> Primitive:
    return Primitive(
        name=name,
        signature="v:=(v,v)",
        parameters=("left", "right"),
        attribute_keys=(),
        implementations=(
            Implementation(
                selector_path=("sse", "si32"),
                extension="sse",
                type_group="si32",
                body_text="complete(left);",
            ),
        ),
    )


def _result() -> GenerationResult:
    coverage = (
        CoverageEntry("unit", "cpp", "add", "sse", "si32"),
        CoverageEntry("unit", "cpp", "add", "sse", "f32"),
        CoverageEntry("unit", "cpp", "sub", "sse", "si32"),
        CoverageEntry("unit", "rust", "add", "sse", "si32"),
        CoverageEntry("unit", "rust", "sub", "sse", "si32"),
        CoverageEntry("cpp_only", "cpp", "add", "sse", "si32"),
    )
    skipped = (
        SkippedEntry(
            "unit",
            "rust",
            "add",
            "sse",
            "f32",
            "not lowered",
        ),
        SkippedEntry(
            "unit",
            "rust",
            "sub",
            "sse",
            "f64",
            "intentionally deferred",
            status="policy_deferred",
        ),
    )
    return GenerationResult(
        artifacts=ArtifactSet.create(()),
        rendered=None,
        diagnostics=(),
        coverage=coverage,
        skipped=skipped,
    )


def _inventory() -> CoverageInventory:
    catalog = Catalog(
        primitives=(_primitive("add"), _primitive("sub")),
        type_groups={},
        extensions={},
        type_spellings={},
        translations={},
    )
    return build_coverage_inventory(
        catalog,
        _result(),
        profiles=("unit", "cpp_only"),
        backends=("cpp", "rust"),
        type_tags=("si32", "f32", "f64"),
        verified_primitives=frozenset({"add"}),
    )


def test_inventory_uses_one_shared_candidate_denominator_per_profile() -> None:
    inventory = _inventory()

    assert inventory.primitive_count == 2
    assert inventory.implementation_count == 2
    assert inventory.emitted_specializations == 6
    assert inventory.average_specializations_per_primitive == 3.0
    assert inventory.aggregate_coverage_percent == pytest.approx(100.0 * 6 / 7)
    assert inventory.mean_primitive_coverage_percent == 90.0
    assert inventory.coverage_gaps == 1
    assert inventory.policy_deferred == 1
    assert inventory.backend_parity is False

    unit = inventory.profile_inventory[0]
    cpp, rust = unit.backends
    assert unit.shared_candidates == 3
    assert (cpp.emitted, cpp.shared_candidates, cpp.coverage_percent) == (3, 3, 100.0)
    assert rust.emitted == 2
    assert rust.shared_candidates == 3
    assert rust.coverage_percent == pytest.approx(100.0 * 2 / 3)
    assert rust.lowering_success_percent == pytest.approx(100.0 * 2 / 3)

    cpp_only = inventory.profile_inventory[1]
    assert cpp_only.backends[0].coverage_percent == 100.0
    assert cpp_only.backends[1].coverage_percent is None


def test_inventory_renderers_explain_counts_and_emit_stable_json() -> None:
    inventory = _inventory()

    text = render_text(inventory)
    assert "Emitted specializations: 6" in text
    assert "2 / 3 (66.7%)" in text
    assert "—" in text

    markdown = render_markdown(inventory)
    assert "Generated by `tslc coverage inventory --format markdown`." in markdown
    assert "## Profile/backend specialization coverage" in markdown
    assert "| `unit` | 3 / 3 (100.0%) | 2 / 3 (66.7%) |" in markdown

    payload = json.loads(render_json(inventory))
    assert payload["corpus"]["primitives"] == 2
    assert payload["specializations"]["emitted"] == 6
    assert payload["profiles"][0]["backends"][1]["coverage_percent"] == pytest.approx(
        100.0 * 2 / 3
    )
    assert payload["profiles"][1]["backends"][1]["coverage_percent"] is None


def test_inventory_command_is_read_only_by_default(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    output = tmp_path / "inventory.md"
    monkeypatch.setattr(coverage_inventory, "_OUT", output)
    monkeypatch.setattr(
        coverage_inventory,
        "collect_inventory",
        lambda **kwargs: (_inventory(), ()),
    )

    status = coverage_inventory.main(
        [
            "--sources",
            str(tmp_path),
            "--machine-profiles",
            str(tmp_path / "profiles.json"),
            "--profiles",
            "unit,cpp_only",
            "--backends",
            "cpp,rust",
        ]
    )

    assert status == 0
    assert "TSLC coverage inventory" in capsys.readouterr().out
    assert not output.exists()


def test_inventory_update_and_check_are_explicit(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    output = tmp_path / "inventory.md"
    monkeypatch.setattr(
        coverage_inventory,
        "collect_inventory",
        lambda **kwargs: (_inventory(), ()),
    )

    assert coverage_inventory.main(["--update", "--output", str(output)]) == 0
    assert output.read_text(encoding="utf-8") == render_markdown(
        _inventory(), tracked=True
    )
    capsys.readouterr()

    assert coverage_inventory.main(["--check", "--output", str(output)]) == 0
    assert "coverage inventory is current" in capsys.readouterr().out


def test_inventory_rejects_output_without_a_write_or_check_mode(
    tmp_path: Path,
) -> None:
    with pytest.raises(SystemExit) as exc:
        coverage_inventory.main(["--output", str(tmp_path / "inventory.md")])

    assert exc.value.code == 2
