"""Public facade for value-test case-plan builders."""

from __future__ import annotations

from tslc.value_tests._case_conversion import (
    convert_case,
    differential_cases,
    extension_harness_available,
    extension_repr_case,
    lane_convert_case,
    load_convert_case,
    repr_cast_case,
)
from tslc.value_tests._case_core import (
    array_to_vector_case,
    broadcast_case,
    compile_only_case,
    compile_failure_case,
    generic_golden_case,
    immediate_case,
    lane_list_case,
    mask_logic_case,
    mask_result_case,
    mask_to_vector_case,
    masked_case,
    reduction_case,
    runtime_failure_case,
    scalar_result_case,
    scalar_vector_case,
    status_pointer_case,
    vector_to_array_case,
)
from tslc.value_tests._case_memory import (
    indexed_load_case,
    indexed_store_case,
    load_case,
    mask_pointer_load_case,
    mask_store_case,
    masked_pointer_load_case,
    masked_pointer_store_case,
    memory_copy_case,
    pointer_free_case,
    pointer_lifetime_case,
    scalar_pointer_load_case,
    store_case,
    stream_case,
)

__all__ = (
    "array_to_vector_case",
    "broadcast_case",
    "compile_only_case",
    "compile_failure_case",
    "convert_case",
    "differential_cases",
    "extension_harness_available",
    "extension_repr_case",
    "generic_golden_case",
    "immediate_case",
    "indexed_load_case",
    "indexed_store_case",
    "lane_list_case",
    "lane_convert_case",
    "load_convert_case",
    "load_case",
    "mask_logic_case",
    "mask_pointer_load_case",
    "mask_result_case",
    "mask_store_case",
    "mask_to_vector_case",
    "masked_case",
    "masked_pointer_load_case",
    "masked_pointer_store_case",
    "memory_copy_case",
    "pointer_free_case",
    "pointer_lifetime_case",
    "reduction_case",
    "runtime_failure_case",
    "repr_cast_case",
    "scalar_pointer_load_case",
    "scalar_result_case",
    "scalar_vector_case",
    "status_pointer_case",
    "store_case",
    "stream_case",
    "vector_to_array_case",
)
