"""Rendering boundaries for generated artifacts."""

from tslgen.rendering.generated_project import (
    GeneratedProjectRenderResult,
    build_generated_project_render_model,
    render_generated_project_skeleton,
)
from tslgen.rendering.primitive_templates import (
    CPP_PRIMITIVE_TEMPLATE_PATH,
    RUST_PRIMITIVE_TEMPLATE_PATH,
    PrimitiveTemplateRenderContext,
    PrimitiveTemplateRenderResult,
    cpp_primitive_template_context,
    render_primitive_templates,
    rust_primitive_template_context,
)
from tslgen.rendering.primitive_render_model import (
    BackendPrimitiveRenderModel,
    PrimitiveArtifactLogicalPath,
    PrimitiveBackendId,
    PrimitiveProfileName,
    PrimitiveRenderContextAdaptationResult,
    PrimitiveRenderRecord,
    PrimitiveRenderSortKey,
    RawTsilPrimitiveRenderValue,
    RenderedImportLine,
    RenderedIncludeLine,
    RenderedModuleText,
    RenderedNamespaceText,
    RenderedPrimitiveBodyText,
    RenderedPrimitiveDeclarationText,
    RenderedPrimitiveDefinitionText,
    UnresolvedPrimitiveRenderValue,
    adapt_primitive_render_models,
    cpp_primitive_render_model,
    rust_primitive_render_model,
)
from tslgen.rendering.supplementary import (
    ProjectSkeletonRenderContext,
    SupplementaryRenderResult,
    SupplementaryStaticAsset,
    SupplementaryTemplateAsset,
    cpp_project_skeleton_assets,
    render_supplementary_assets,
    rust_project_skeleton_assets,
)

__all__ = [
    "GeneratedProjectRenderResult",
    "CPP_PRIMITIVE_TEMPLATE_PATH",
    "ProjectSkeletonRenderContext",
    "PrimitiveTemplateRenderContext",
    "PrimitiveTemplateRenderResult",
    "RUST_PRIMITIVE_TEMPLATE_PATH",
    "BackendPrimitiveRenderModel",
    "PrimitiveArtifactLogicalPath",
    "PrimitiveBackendId",
    "PrimitiveProfileName",
    "PrimitiveRenderContextAdaptationResult",
    "PrimitiveRenderRecord",
    "PrimitiveRenderSortKey",
    "RawTsilPrimitiveRenderValue",
    "RenderedImportLine",
    "RenderedIncludeLine",
    "RenderedModuleText",
    "RenderedNamespaceText",
    "RenderedPrimitiveBodyText",
    "RenderedPrimitiveDeclarationText",
    "RenderedPrimitiveDefinitionText",
    "SupplementaryRenderResult",
    "SupplementaryStaticAsset",
    "SupplementaryTemplateAsset",
    "UnresolvedPrimitiveRenderValue",
    "adapt_primitive_render_models",
    "build_generated_project_render_model",
    "cpp_project_skeleton_assets",
    "cpp_primitive_render_model",
    "cpp_primitive_template_context",
    "render_primitive_templates",
    "render_generated_project_skeleton",
    "render_supplementary_assets",
    "rust_primitive_render_model",
    "rust_primitive_template_context",
    "rust_project_skeleton_assets",
]
