// Generated by tslgen clean-room backend slice.
// Backend: cpp
// Artifact: generated.hpp
// Artifact kind: generated
// Candidates: 2
// Definitions: 2
// Required flags: sse
// Target extensions: scalar

#pragma once

#include <cstdint>

namespace tsl {
namespace generated {

struct primitive_candidate {
  const char* primitive;
  const char* template_name;
  const char* target_extension;
  const char* source_extension;
  const char* type_tag;
  const char* required_flags;
  const char* body_kind;
  const char* opaque_tsil_payload;
};

inline constexpr primitive_candidate primitive_candidates[] = {
  {
    "slice_add",
    "binary",
    "scalar",
    "scalar",
    "si32",
    "sse",
    "tsil",
    "emit_return(left + right);",
  },
  {
    "slice_add",
    "binary",
    "scalar",
    "scalar",
    "ui32",
    "sse",
    "tsil",
    "emit_return(left + right);",
  },
};

namespace production {

inline std::int32_t slice_add_si32(std::int32_t left, std::int32_t right) {
  return left + right;
}

inline std::uint32_t slice_add_ui32(std::uint32_t left, std::uint32_t right) {
  return left + right;
}

}  // namespace production

}  // namespace generated
}  // namespace tsl
