from __future__ import annotations

from tslgen.analysis.candidates import ImplementationCandidate
from tslgen.core.frozen_map import FrozenMap
from tslgen.core.result import Result
from tslgen.io.artifacts import Artifact, ArtifactSet, artifact_set_from_artifacts

from .planner import RustRenderJob, RustRenderPlan


def render_rust_plan(plan: RustRenderPlan) -> Result[ArtifactSet]:
    artifacts = tuple(_render_job(job) for job in plan.jobs)
    return artifact_set_from_artifacts(artifacts, metadata=plan.metadata)


def _render_job(job: RustRenderJob) -> Artifact:
    content = _render_generated_module(job)
    return Artifact(
        logical_path=job.descriptor.logical_path,
        content=content,
        metadata=FrozenMap(
            {
                "artifact_kind": job.descriptor.kind,
                "backend_id": "rust",
                "candidate_count": len(job.candidates),
                "required_flags": _required_flag_names(job.candidates),
                "target_extensions": _target_extension_names(job.candidates),
            }
        ),
    )


def _render_generated_module(job: RustRenderJob) -> str:
    required_flags = _csv(_required_flag_names(job.candidates))
    target_extensions = _csv(_target_extension_names(job.candidates))
    lines = [
        "// Generated by tslgen clean-room backend slice.",
        "// Backend: rust",
        f"// Artifact: {job.descriptor.logical_path.as_posix()}",
        f"// Artifact kind: {job.descriptor.kind}",
        f"// Candidates: {len(job.candidates)}",
        f"// Required flags: {required_flags}",
        f"// Target extensions: {target_extensions}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct PrimitiveCandidate {",
        "    pub primitive: &'static str,",
        "    pub template_name: &'static str,",
        "    pub target_extension: &'static str,",
        "    pub source_extension: &'static str,",
        "    pub type_tag: &'static str,",
        "    pub required_flags: &'static str,",
        "    pub body_kind: &'static str,",
        "    pub opaque_tsil_payload: &'static str,",
        "}",
        "",
        "pub const PRIMITIVE_CANDIDATES: &[PrimitiveCandidate] = &[",
    ]
    for candidate in job.candidates:
        lines.extend(_candidate_lines(candidate))
    lines.extend(
        [
            "];",
            "",
        ]
    )
    return "\n".join(lines)


def _candidate_lines(candidate: ImplementationCandidate) -> tuple[str, ...]:
    body = candidate.implementation.body
    payload = body.payload if isinstance(body.payload, str) else ""
    required_flags = _csv(tuple(flag.name for flag in candidate.required_flags))
    return (
        "    PrimitiveCandidate {",
        f"        primitive: {_rust_string(candidate.emitted_primitive_name)},",
        f"        template_name: {_rust_string(candidate.template_name)},",
        f"        target_extension: {_rust_string(candidate.target_extension)},",
        f"        source_extension: {_rust_string(candidate.source_extension)},",
        f"        type_tag: {_rust_string(candidate.type_tag)},",
        f"        required_flags: {_rust_string(required_flags)},",
        f"        body_kind: {_rust_string(body.kind)},",
        f"        opaque_tsil_payload: {_rust_string(payload)},",
        "    },",
    )


def _required_flag_names(
    candidates: tuple[ImplementationCandidate, ...],
) -> tuple[str, ...]:
    return tuple(
        sorted(
            {
                flag.name
                for candidate in candidates
                for flag in candidate.required_flags
            }
        )
    )


def _target_extension_names(
    candidates: tuple[ImplementationCandidate, ...],
) -> tuple[str, ...]:
    return tuple(sorted({candidate.target_extension for candidate in candidates}))


def _csv(values: tuple[str, ...]) -> str:
    return ", ".join(values) if values else "none"


def _rust_string(value: str) -> str:
    replacements: dict[str, str] = {
        "\\": "\\\\",
        '"': '\\"',
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
    }
    escaped = "".join(replacements.get(character, character) for character in value)
    return f'"{escaped}"'
